/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Account = IDL.Record({
  'studentId' : IDL.Nat,
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'initialAmount' : IDL.Nat,
  'accountNumber' : IDL.Text,
  'className' : IDL.Text,
});
export const BankDetail = IDL.Record({
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'district' : IDL.Text,
  'taluka' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'attendanceNumber' : IDL.Nat,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'district' : IDL.Text,
  'taluka' : IDL.Text,
  'className' : IDL.Text,
  'schoolName' : IDL.Text,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Text,
  'studentName' : IDL.Text,
  'date' : Time,
  'totalAmount' : IDL.Nat,
  'runningBalance' : IDL.Nat,
  'accountNumber' : IDL.Text,
  'amount' : IDL.Nat,
  'previousBalance' : IDL.Nat,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'accountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addBankDetail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAccount' : IDL.Func([IDL.Text], [], []),
  'deleteBankDetail' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [Result], []),
  'getAccountByNumber' : IDL.Func([IDL.Text], [Account], ['query']),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllBankDetails' : IDL.Func([], [IDL.Vec(BankDetail)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactionsByAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateBankDetail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateStudent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Account = IDL.Record({
    'studentId' : IDL.Nat,
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'initialAmount' : IDL.Nat,
    'accountNumber' : IDL.Text,
    'className' : IDL.Text,
  });
  const BankDetail = IDL.Record({
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'district' : IDL.Text,
    'taluka' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'attendanceNumber' : IDL.Nat,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'district' : IDL.Text,
    'taluka' : IDL.Text,
    'className' : IDL.Text,
    'schoolName' : IDL.Text,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Text,
    'studentName' : IDL.Text,
    'date' : Time,
    'totalAmount' : IDL.Nat,
    'runningBalance' : IDL.Nat,
    'accountNumber' : IDL.Text,
    'amount' : IDL.Nat,
    'previousBalance' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addBankDetail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAccount' : IDL.Func([IDL.Text], [], []),
    'deleteBankDetail' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [Result], []),
    'getAccountByNumber' : IDL.Func([IDL.Text], [Account], ['query']),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllBankDetails' : IDL.Func([], [IDL.Vec(BankDetail)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactionsByAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateBankDetail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateStudent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };