/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'studentId' : bigint,
  'ifscCode' : string,
  'bankName' : string,
  'initialAmount' : bigint,
  'accountNumber' : string,
  'className' : string,
}
export interface BankDetail {
  'ifscCode' : string,
  'bankName' : string,
  'district' : string,
  'taluka' : string,
}
export interface Student {
  'id' : bigint,
  'attendanceNumber' : bigint,
  'dateOfBirth' : string,
  'name' : string,
  'district' : string,
  'taluka' : string,
  'className' : string,
  'schoolName' : string,
}
export type Time = bigint;
export interface Transaction {
  'transactionType' : string,
  'studentName' : string,
  'date' : Time,
  'totalAmount' : bigint,
  'runningBalance' : bigint,
  'accountNumber' : string,
  'amount' : bigint,
  'previousBalance' : bigint,
  'reason' : string,
}
export interface UserProfile { 'name' : string, 'accountNumber' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccount' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'addBankDetail' : ActorMethod<[string, string, string, string], undefined>,
  'addStudent' : ActorMethod<
    [string, string, string, bigint, string, string, string],
    bigint
  >,
  'addTransaction' : ActorMethod<[string, string, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAccount' : ActorMethod<[string], undefined>,
  'deleteBankDetail' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'getAccountByNumber' : ActorMethod<[string], Account>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllBankDetails' : ActorMethod<[], Array<BankDetail>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTransactionsByAccount' : ActorMethod<[string], Array<Transaction>>,
  'getTransactionsByDateRange' : ActorMethod<[Time, Time], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAccount' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'updateBankDetail' : ActorMethod<[string, string, string, string], undefined>,
  'updateStudent' : ActorMethod<
    [bigint, string, string, string, bigint, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];